### ISSUE TITLE
viewController doesn't call deinit anymore.

### ISSUE THREAD

**Issue by wangjiejacques** [smartlook/smartlook-ios-sdk#3] opened 2018-09-04 09:18 UTC
After integrating smartlook, it seems all the view controller doesn't call `deinit` any more.

**Comment by pavel-kroh-smartlook** [comment] 2018-11-20 18:13
Hi @wangjiejacques, first apologies for a bit delayed response. 

We have been investigating the issue and **cannot reproduce it**. 

Would you share some more details about the affected project with us? 

Is is a standard iOS project or do you use some unusual programming techniques in it? 

What version of  Smartlook iOS SDK is used?

What is your Smartlook account so we can investigate the app recordings?

Thanks for any hint.

**Comment by pavel-kroh-smartlook** [comment] 2019-04-18 09:58
As we are unable reproducing this issue, and there were several new versions of SDK released in the meantime, I'm closing it. Feel free to reopen it if the issue persists in  the lates version of SDK and your app.

**Closed by pavel-kroh-smartlook** 2019-04-18 09:58 UTC
Labels: question
